Repository willowtreeapps/vocable-android, pull requests merged in 2022-05, with the labels that each got.

#354 Database rewrite
  app/build.gradle
  app/schemas/com.willowtree.vocable.room.VocableDatabase/6.json
  app/src/androidTest/java/com/willowtree/vocable/room/MigrationTest.kt
  app/src/androidTest/java/com/willowtree/vocable/tests/BaseTest.kt
  app/src/main/java/com/willowtree/vocable/BaseActivity.kt
  app/src/main/java/com/willowtree/vocable/VocableApp.kt
  app/src/main/java/com/willowtree/vocable/keyboard/KeyboardFragment.kt
  app/src/main/java/com/willowtree/vocable/keyboard/KeyboardViewModel.kt
  app/src/main/java/com/willowtree/vocable/presets/PresetCategories.kt
  app/src/main/java/com/willowtree/vocable/presets/PresetsFragment.kt
  app/src/main/java/com/willowtree/vocable/presets/PresetsRepository.kt
  app/src/main/java/com/willowtree/vocable/presets/PresetsViewModel.kt
  app/src/main/java/com/willowtree/vocable/presets/adapter/AddToCategoryPickerViewModel.kt
  app/src/main/java/com/willowtree/vocable/room/Category.kt
  app/src/main/java/com/willowtree/vocable/room/CategoryDao.kt
  app/src/main/java/com/willowtree/vocable/room/CategoryPhraseCrossRef.kt
  app/src/main/java/com/willowtree/vocable/room/CategoryPhraseCrossRefDao.kt
  app/src/main/java/com/willowtree/vocable/room/CategoryWithPhrases.kt
  app/src/main/java/com/willowtree/vocable/room/Phrase.kt
  app/src/main/java/com/willowtree/vocable/room/PhraseDao.kt
  app/src/main/java/com/willowtree/vocable/room/VocableDatabase.kt
  app/src/main/java/com/willowtree/vocable/room/VocableDatabaseMigrations.kt
  app/src/main/java/com/willowtree/vocable/settings/AddPhraseViewModel.kt
  app/src/main/java/com/willowtree/vocable/settings/AddUpdateCategoryViewModel.kt
  app/src/main/java/com/willowtree/vocable/settings/EditCategoriesListFragment.kt
  app/src/main/java/com/willowtree/vocable/settings/EditCategoriesViewModel.kt
  app/src/main/java/com/willowtree/vocable/settings/EditCategoryOptionsFragment.kt
  app/src/main/java/com/willowtree/vocable/settings/EditPhrasesViewModel.kt
  app/src/main/java/com/willowtree/vocable/splash/SplashViewModel.kt
  app/src/main/java/com/willowtree/vocable/utils/LocalizedResourceUtility.kt
  app/src/main/java/com/willowtree/vocable/utils/VocableSharedPreferences.kt
Labels: Testing in progress...

#365 Feature/355 UI Refactor Part 1: Categories List in Settings
  app/src/main/java/com/willowtree/vocable/presets/PresetCategories.kt
  app/src/main/java/com/willowtree/vocable/presets/PresetsFragment.kt
  app/src/main/java/com/willowtree/vocable/settings/EditCategoriesListFragment.kt
  app/src/main/res/drawable/ic_down_arrow.xml
  app/src/main/res/drawable/ic_up_arrow.xml
  app/src/main/res/layout/category_edit_button.xml
  app/src/main/res/layout/fragment_edit_categories.xml
  app/src/main/res/values-land/dimens.xml
  app/src/main/res/values-sw600dp-land/dimens.xml
  app/src/main/res/values-sw600dp/dimens.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: Testing Completed

#374 Removed add to categories from keyboard
  app/src/main/java/com/willowtree/vocable/BaseViewModelFactory.kt
  app/src/main/java/com/willowtree/vocable/keyboard/KeyboardFragment.kt
  app/src/main/java/com/willowtree/vocable/presets/AddToCategoryPickerFragment.kt
  app/src/main/java/com/willowtree/vocable/presets/AddToCategoryPickerListFragment.kt
  app/src/main/java/com/willowtree/vocable/presets/adapter/AddToCategoryPickerViewModel.kt
  app/src/main/java/com/willowtree/vocable/settings/AddPhraseKeyboardFragment.kt
  app/src/main/java/com/willowtree/vocable/settings/EditPhrasesKeyboardFragment.kt
  app/src/main/res/layout-land/keyboard_action_buttons.xml
  app/src/main/res/layout-sw600dp/keyboard_action_buttons.xml
  app/src/main/res/layout/fragment_add_to_category_list.xml
  app/src/main/res/layout/fragment_add_to_category_picker.xml
  app/src/main/res/layout/keyboard_action_buttons.xml
  app/src/main/res/navigation/main_nav_graph.xml
Labels: Testing Completed

#378 Back when save new text and toast
  app/src/main/java/com/willowtree/vocable/keyboard/KeyboardFragment.kt
  app/src/main/java/com/willowtree/vocable/settings/AddPhraseKeyboardFragment.kt
  app/src/main/java/com/willowtree/vocable/settings/AddPhraseViewModel.kt
  app/src/main/java/com/willowtree/vocable/settings/EditCategoriesKeyboardFragment.kt
  app/src/main/java/com/willowtree/vocable/settings/EditCategoryOptionsFragment.kt
  app/src/main/java/com/willowtree/vocable/settings/EditPhrasesKeyboardFragment.kt
  app/src/main/java/com/willowtree/vocable/settings/EditPhrasesViewModel.kt
  app/src/main/java/com/willowtree/vocable/settings/customcategories/CustomCategoryPhraseListFragment.kt
  app/src/main/java/com/willowtree/vocable/settings/customcategories/adapter/CustomCategoryPhraseAdapter.kt
  app/src/main/res/layout-land/fragment_edit_keyboard.xml
  app/src/main/res/layout-land/fragment_keyboard.xml
  app/src/main/res/layout-sw600dp-land/fragment_edit_keyboard.xml
  app/src/main/res/layout-sw600dp-land/fragment_keyboard.xml
  app/src/main/res/layout-sw600dp/fragment_edit_keyboard.xml
  app/src/main/res/layout-sw600dp/fragment_keyboard.xml
  app/src/main/res/layout/fragment_edit_keyboard.xml
  app/src/main/res/layout/fragment_keyboard.xml
  app/src/main/res/layout/phrase_saved_success.xml
  app/src/main/res/values/strings.xml
Labels: Testing Completed

#377 Fixed bug where the starting category would not be selected initially
  app/src/main/java/com/willowtree/vocable/presets/PresetsFragment.kt
Labels: Testing Completed

#376 fixed layout for sw600dp and landscape category
  app/src/main/java/com/willowtree/vocable/settings/EditCategoriesListFragment.kt
  app/src/main/res/layout-land/category_edit_button.xml
  app/src/main/res/layout-sw600dp/category_edit_button.xml
  app/src/main/res/values-sw600dp/dimens.xml
Labels: Design Updates, Testing Completed

#379 Add "+ add phrase" button
  app/src/main/java/com/willowtree/vocable/customviews/KeyboardButton.kt
  app/src/main/java/com/willowtree/vocable/customviews/NoSayTextButton.kt
  app/src/main/java/com/willowtree/vocable/presets/NumberPadFragment.kt
  app/src/main/java/com/willowtree/vocable/presets/PhrasesFragment.kt
  app/src/main/java/com/willowtree/vocable/presets/PresetsFragment.kt
  app/src/main/java/com/willowtree/vocable/presets/PresetsViewModel.kt
  app/src/main/java/com/willowtree/vocable/presets/adapter/PhraseAdapter.kt
  app/src/main/java/com/willowtree/vocable/settings/EditCategoriesListFragment.kt
  app/src/main/res/drawable/button_background_dashed.xml
  app/src/main/res/drawable/button_default_background_dashed.xml
  app/src/main/res/drawable/button_highlighted_background_dashed.xml
  app/src/main/res/layout-land/fragment_edit_category_options.xml
  app/src/main/res/layout-land/fragment_presets.xml
  app/src/main/res/layout-land/fragment_settings.xml
  app/src/main/res/layout-sw600dp-land/fragment_edit_category_options.xml
  app/src/main/res/layout-sw600dp-land/fragment_settings.xml
  app/src/main/res/layout-sw600dp/fragment_edit_category_options.xml
  app/src/main/res/layout-sw600dp/fragment_presets.xml
  app/src/main/res/layout-sw600dp/fragment_settings.xml
  app/src/main/res/layout-sw600dp/vocable_confirmation_dialog.xml
  app/src/main/res/layout/category_edit_button.xml
  app/src/main/res/layout/fragment_edit_category_options.xml
  app/src/main/res/layout/fragment_keyboard_2_stroke_ff.xml
  app/src/main/res/layout/fragment_presets.xml
  app/src/main/res/layout/fragment_settings.xml
  app/src/main/res/layout/keyboard_key_layout.xml
  app/src/main/res/layout/phrase_button.xml
  app/src/main/res/layout/phrase_button_add.xml
  app/src/main/res/layout/settings_options_layout.xml
  app/src/main/res/layout/vocable_confirmation_dialog.xml
  app/src/main/res/navigation/main_nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: Testing Completed, v1.5.1

#375 Feature/355 category settings UI refactor part 2
  app/src/main/java/com/willowtree/vocable/BaseViewModelFactory.kt
  app/src/main/java/com/willowtree/vocable/VocableApp.kt
  app/src/main/java/com/willowtree/vocable/presets/CategoriesFragment.kt
  app/src/main/java/com/willowtree/vocable/presets/PresetsFragment.kt
  app/src/main/java/com/willowtree/vocable/presets/PresetsViewModel.kt
  app/src/main/java/com/willowtree/vocable/settings/AddUpdateCategoryViewModel.kt
  app/src/main/java/com/willowtree/vocable/settings/EditCategoriesKeyboardFragment.kt
  app/src/main/java/com/willowtree/vocable/settings/EditCategoriesListFragment.kt
  app/src/main/java/com/willowtree/vocable/settings/EditCategoriesViewModel.kt
  app/src/main/java/com/willowtree/vocable/settings/EditCategoryMenuFragment.kt
  app/src/main/java/com/willowtree/vocable/settings/EditCategoryMenuViewModel.kt
  app/src/main/java/com/willowtree/vocable/settings/EditCategoryPhrasesFragment.kt
  app/src/main/java/com/willowtree/vocable/settings/customcategories/CustomCategoryPhraseListFragment.kt
  app/src/main/java/com/willowtree/vocable/settings/customcategories/adapter/CustomCategoryPhraseAdapter.kt
  app/src/main/java/com/willowtree/vocable/utils/LocalizedResourceUtility.kt
  app/src/main/java/com/willowtree/vocable/utils/VocableSharedPreferences.kt
  app/src/main/res/.DS_Store
  app/src/main/res/drawable/button_background_remove_category.xml
  app/src/main/res/drawable/button_default_background_remove_category.xml
  app/src/main/res/layout-land/category_edit_button.xml
  app/src/main/res/layout-land/edit_custom_category_phrase_item.xml
  app/src/main/res/layout-land/fragment_edit_category_menu.xml
  app/src/main/res/layout-land/fragment_edit_category_phrases.xml
  app/src/main/res/layout-sw600dp-land/fragment_edit_category_phrases.xml
  app/src/main/res/layout-sw600dp/category_edit_button.xml
  app/src/main/res/layout-sw600dp/fragment_edit_category_phrases.xml
  app/src/main/res/layout-sw600dp/vocable_confirmation_dialog.xml
  app/src/main/res/layout/edit_custom_category_phrase_item.xml
  app/src/main/res/layout/fragment_edit_category_menu.xml
  app/src/main/res/layout/fragment_edit_category_phrases.xml
  app/src/main/res/layout/selection_mode_options_layout.xml
  app/src/main/res/layout/vocable_confirmation_dialog.xml
  app/src/main/res/navigation/main_nav_graph.xml
  app/src/main/res/values-land/integers.xml
  app/src/main/res/values/integers.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: Testing in progress..., Testing requests changes
